### ISSUE TITLE
Not opening GP and GPX files but opens GP5 Files

### ISSUE THREAD

**Issue by DivannKokos** [rageagainsthepc/GuitarPro-to-Midi#11]
Idk if there is somebody alive but i can't open any gp or gpx file
```
GuitarProToMidi gpx.gp -v
Error: Input string was not in a correct format.
   at System.Environment.get_StackTrace()
   at GuitarProToMidi.Program.Main(String[] args)
```

**Comment by rageagainsthepc** [comment]
Hi, which OS are you using?

**Comment by rageagainsthepc** [comment]
I've also noticed a mistake which made the stack traces pretty much useless. If you would download the newly released version and paste that stack trace here that would be a better starting point for a root cause search.

**Comment by DivannKokos** [comment]
Windows 10 20H2, build 19042.928

**Comment by DivannKokos** [comment]
here stack trace

Error: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at GP6File.transferTracks(Node nTracks, GP5File song)
   at GP6File.GP6NodeToGP5File(Node node)
   at GP6File.readSong()
   at GuitarProToMidi.GpFileParser.CreateMidiFile()
   at GuitarProToMidi.Program.<>c__DisplayClass0_0.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at GuitarProToMidi.Program.Main(String[] args)

**Comment by DivannKokos** [comment]
same stack trace not only for gpx file but and gp file

**Comment by DivannKokos** [comment]
my guitar pro (in what files for test been created)
7.5.4 build 1788

**Comment by DivannKokos** [comment]
> my guitar pro (in what files for test been created)
> 7.5.4 build 1788

i updated to 7.5.5 buld 1844, create new test file and still get error so it not because of version of my guitar pro  i think

**Comment by rageagainsthepc** [comment]
What's interesting is that the file is parsed as a GP 6 file although you say you have created it with GP 7.5.5. 🤔 
You could send me a minimal example file with which it is possible to reproduce the error and I will have a look at it as time permits.

**Comment by DivannKokos** [comment]
I noticed that if i export GP file in to GP5 then it works without a single error!

Export to GP file from GP file: error 
Export to GPX file from GP file: error (same error as GP)
Export to GP5 file from GP file: magically works

[test file](https://drive.google.com/file/d/1DdkWnq9kTyneY2Y2FvJ063DHBkiQyTJz/view?usp=sharing)

**Comment by rageagainsthepc** [comment]
It's probably a bug in the parser. I'll have a look. Thanks for the test file :+1:

**Comment by rageagainsthepc** [comment]
@DivannKokos I can't reproduce the error with your test file. It is converted without any problems. 🤷‍♂️

**Comment by rageagainsthepc** [comment]
Ok, cool. Thanks for your effort. 👍
I thought about it as well, but the stack trace seems to indicate that some integer conversion isn't working which should have nothing to do with you having a russian localization of Windows. Also, let's say you have entered some cyrillic strings somewhere (e. g. for a track name) then this should also be a problem if I try to convert the same file on my machine. I really have no idea why there should be a discrepancy between our two systems. 🤔

**Comment by DivannKokos** [comment]
> Ok, cool. Thanks for your effort. 👍
> I thought about it as well, but the stack trace seems to indicate that some integer conversion isn't working which should have nothing to do with you having a russian localization of Windows. Also, let's say you have entered some cyrillic strings somewhere (e. g. for a track name) then this should also be a problem if I try to convert the same file on my machine. I really have no idea why there should be a discrepancy between our two systems. 🤔

no, i never write cyrillic names except my cyrillic name of user of pc, but if i will reinstalling windows i will write on latin)

**Comment by DivannKokos** [comment]
Well
If this dont because of language of windows, but it because of region format
If i change my region format to e.g English UK, then in successfully convert, but if i change it back to russian, then it gives already known error

To reproduce error:
Change region format in settings of windows to anything, but not English
Then error will be

**Comment by DivannKokos** [comment]
Language Russian, regional settings: English UK - successfully convert
Language Russian, regional settings: anything but not English - error

**Comment by rageagainsthepc** [comment]
So yeah, it turns out the localization does make a difference for parsing numbers because some locales use ',' as decimal separator while others use '.'. ;) The funny thing is: I'm on German localization and should therefore have the same issues but I don't and I have no clue why. 🤔

**Comment by rageagainsthepc** [comment]
@DivannKokos Thanks for your help. I've released a new version that should not have this issue anymore.
