### ISSUE TITLE
How to run in WSL2

### ISSUE THREAD

**Issue by juancopi81** [rageagainsthepc/GuitarPro-to-Midi#27]
Hi,

Sorry if this is too obvious. I could not find. I was wondering if I could run the program in WSL2 and, if so, how. I downloaded the last release but I am unsure on how to proceed after that.

Thanks!

**Comment by rageagainsthepc** [comment]
I am not sure what you mean. Did you download the windows release or the linux release? For WSL you would need the linux release, but I am not sure what you are trying to accomplish. If you have downloaded the windows release, your best pick would be powershell.

**Comment by juancopi81** [comment]
Hi @rageagainsthepc, 

Thanks for your response. I solved it. I was just not sure how to proceed after downloading the linux release. But I just chmoded and then run it with sudo, and it worked fine.

Thanks a lot!
