### ISSUE TITLE
Error: Index was out of range. (Parameter 'index')

### ISSUE THREAD

**Issue by Ayfri** [rageagainsthepc/GuitarPro-to-Midi#6]
Hi, I'm trying to convert a .gp5 file but I'm getting this `Error: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`, why does it occurs?

**Comment by rageagainsthepc** [comment]
Hm, impossible to say without knowing where the error originates from. I should add stack trace printing to the `--verbose` option. You could also remove the exception handling in `Program.cs` and paste the stack trace here.

**Comment by rageagainsthepc** [comment]
I have released a new version. Now you should see a stack trace if you try to convert your file with `-v`.

**Comment by Ayfri** [comment]
Okay now I'm not getting the error again, weirdo 🤔

**Comment by rageagainsthepc** [comment]
Ok, I think I know what's going on. I am pretty sure that I have already stumbled upon this bug myself. It's already fixed but up until now there was no release with the bugfix included. The bug occurs when there are empty tracks present in the gp file.

**Comment by Ayfri** [comment]
Oh yeah it was that !
